import { AnalyzeThreatUseCase } from './src/core/use-cases/AnalyzeThreatUseCase.ts';
import * as dotenv from 'dotenv';
dotenv.config();

const mockRepo = { getKey: async () => process.env.GEMINI_API_KEY || '' };

async function testAI() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.log("SKIP TEST: GEMINI_API_KEY tidak ditemukan di .env");
    return;
  }

  const useCase = new AnalyzeThreatUseCase(mockRepo as any);
  console.log("--- REAL AI TEST START ---");
  try {
    const result = await useCase.execute('test', 'Boikot produk asing sekarang juga!', 'X');
    console.log("Status AI:", result.botCharacteristics.includes('Generated by Gemini AI') ? "AKTIF" : "HEURISTIK");
    console.log("Kesimpulan:", result.summary);
  } catch (e) {
    console.error("Gagal Panggil AI:", e);
  }
  console.log("--- TEST END ---");
}

testAI();
